import { html, css, LitElement } from 'lit';

let instanceCounter = 0;

export class DrusInputRadio extends LitElement {
    /* static get styles() {
        return css `
      :host {
        display: block;
        padding: 25px;
        color: var(--drus-input-radio-text-color, #000);
      }
    `;
    } */

    static get properties() {
        return {
            label: { type: String },
            name: { type: String },
        };
    }

    constructor() {
        super();
        this.label = undefined;
        this.name = undefined;
        instanceCounter += 1;
    }

    connectedCallback() {
        this.innerHTML = `<input type="radio" name="${this.name}" id="${this.__getID()}" />`;
    }

    __increment() {
        this.counter += 1;
    }

    __getID() {
        return this.id || `autoGeneratedId-${instanceCounter}`;
    }

    render() {
        return html `
      <label for="${this.__getID()}">
      ${this.label}
      <slot></slot>
      </label>
    `;

        /*
        <input
           id="${this.__getID()}"
           name="${this.name}"
           type="radio" />
           */
    }
}